### ISSUE TITLE
Setting up with docker-compose

### ISSUE THREAD

**Issue by ghost** [k-labs/docker-forgetproxy#3]
Hi,

Do you have any example of configuration with Docker-compose ?

Best regards,

André

**Comment by benoitvidis** [comment]
Did not try it, but the following should work if your `http_proxy` and `https_proxy` environment variables are properly set:

```yaml
version: '2'

services:
  proxy:
    image: klabs/forgetproxy
    privileged: true
    network_mode: host
    environment:
      - http_proxy
      - https_proxy
```

**Comment by PhilippHeuer** [comment]
It does work ;)

This is my `docker-compose.yml`
```
version: '3.2'
services:
  app:
    # Image
    image: klabs/forgetproxy
    restart: unless-stopped
    # Permissions
    privileged: true
    # Environment
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
    # Networks
    network_mode: host
```

I used `${http_proxy}` to pass on the configuration of my host, which is really nice.

Just a note: This only works for applications using `docker0`, so it won't work for your other docker-compose applications, if they create their own networks.

E: NVM. Just set `network_mode: bridge` to use the docker0 in your docker-compose files.

--
Thanks for the great project, all of those proxy issues were really getting on my nerves.
